server:
  port: 7011
spring:
  application:
    name: lab-auth
eureka:
  instance:
    hostname: localhost
    instance-id: AuthModule
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka
