mybatis-plus:
  type-aliases-package: com.github.laboratory.entity
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: DbPassword
      jdbc-url: jdbc:mysql://www.seven-io.top:6306/laboratory?characterEncoding=utf-8
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: DbPassword
      jdbc-url: jdbc:mysql://www.seven-io.top:6307/laboratory?characterEncoding=utf-8   # 这个地方必须写成jdbc-url
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    username: root
    #    password: DbPassword
    #    url: jdbc:mysql://www.seven-io.top:6306/laboratory?characterEncoding=utf-8
  redis:
    host: www.seven-io.top
    port: 6379
    password: RedisPassword
    database: 0